import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:skeleton/skeleton.dart';

/// Defines a standard interface for all API service classes, enforcing common CRUD operations.
///
/// This abstract class is designed to be implemented by a concrete service class generated by the `retrofit` package.
///
/// Type Parameters:
/// - [Model]: The data model representing the resource (e.g., `User`, `Product`).
/// - [EditRequest]: The model used for C/U (Create/Update) requests (e.g., `UserCreateRequest`).
/// - [SearchRequest]: The model used for query and filtering parameters (e.g., `UserSearchParams`).
abstract class BaseApiService<Model, EditRequest, SearchRequest> {
  BaseApiService(Dio dio, {String? baseUrl});

  /// Retrieves a single resource by its ID.
  ///
  /// @param id The requested resource id.
  /// @param params Optional parameters (filters, fields selector).
  /// @returns A [BasicResponse<Model>] containing the requested resource or error information.
  @GET("/{id}")
  Future<BasicResponse<Model>> show({@Path('id') required int id, @Queries() SearchRequest? params}) => throw UnimplementedError();

  /// Retrieves a single resource, typically used to get raw data specifically for
  /// pre-filling an editing form (may return more fields than the regular [show] method).
  @GET("/{id}/edit")
  Future<BasicResponse<Model>> showForEdit({@Path('id') required int id, @Queries() SearchRequest? params}) => throw UnimplementedError();

  /// Gets all resources at once, without pagination. Use with caution for large datasets.
  @GET("")
  Future<BasicResponse<List<Model>>> all({@Queries() required SearchRequest request}) => throw UnimplementedError();

  /// Retrieves resources using pagination.
  ///
  /// @param page The requested page number (e.g., 1, 2, 3...).
  /// @param request Additional query parameters used for filtering and pagination settings (like `perPage`, `_fields[]`).
  /// @returns A [BasicResponse] wrapping a [PaginationResponse<Model>] object.
  @GET("")
  Future<BasicResponse<PaginationResponse<Model>>> paging({@Query('page') required int page, @Queries() required SearchRequest request}) => throw UnimplementedError();

  /// Retrieves resources at once, without pagination, but targets a custom or administrative endpoint.
  @GET("/{path}")
  Future<BasicResponse<List<Model>>> allCustomPath({@Path('path') required String path, @Queries() required SearchRequest request}) => throw UnimplementedError();

  /// Retrieves resources using pagination but targets a custom or administrative endpoint.
  ///
  /// This method is intended for custom contexts where the data might differ or require specific security clearance.
  @GET("/{path}")
  Future<BasicResponse<PaginationResponse<Model>>> pagingCustomPath({
    @Path('path') required String path,
    @Query('page') required int page,
    @Queries() required SearchRequest request,
  }) => throw UnimplementedError();

  /// Deletes a resource by its ID.
  ///
  /// @param id The resource id that will be deleted.
  /// @param params Optional query parameters.
  /// @returns A [BasicResponse<int>] typically returning the deleted resource ID.
  @DELETE("/{id}")
  Future<BasicResponse<int>> delete({@Path('id') required int id, @Queries() SearchRequest? params}) => throw UnimplementedError();

  /// Creates a new resource.
  ///
  /// @param request The data model containing the new resource's attributes.
  /// @returns A [BasicResponse<int>] typically returning the ID of the newly created resource.
  @POST("")
  Future<BasicResponse<int>> create(@Body() EditRequest request) => throw UnimplementedError();

  /// Updates an existing resource by its ID.
  ///
  /// [id] The ID of the resource to update.
  /// [request] The data model containing the updated attributes.
  /// @returns A [BasicResponse<int>] typically returning the updated resource ID or a status code.
  @PUT("/{id}")
  Future<BasicResponse<int>> update({@Path('id') required int id, @Body() required EditRequest request}) => throw UnimplementedError();

  /// Manage resource relationships.
  ///
  /// [id] is the ID of the parent model being modified.
  /// [request] is the payload defining the relationship to change.
  @PATCH("/{id}/relations")
  Future<BasicResponse> manageRelations({@Path('id') required int id, @Body() required ManageRelationRequest request}) => throw UnimplementedError();
}
